<?php 
$setting['cate_models']['return']=array (
  'id' => '16',
  'name' => 'return',
  'description' => '用户回复',
  'perpage' => '12',
  'level' => '1',
  'hasattach' => '0',
  'built_in' => '0',
  'fields' => 
  array (
    93 => 
    array (
      'id' => '93',
      'name' => 'fromid',
      'description' => '被评论人',
      'model' => '16',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    94 => 
    array (
      'id' => '94',
      'name' => 'comeid',
      'description' => '评论人',
      'model' => '16',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    95 => 
    array (
      'id' => '95',
      'name' => 'content',
      'description' => '内容',
      'model' => '16',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    96 => 
    array (
      'id' => '96',
      'name' => 'time',
      'description' => '评论时间',
      'model' => '16',
      'type' => 'datetime',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '93',
    1 => '94',
    2 => '95',
    3 => '96',
  ),
  'searchable' => 
  array (
    0 => '93',
    1 => '94',
    2 => '95',
    3 => '96',
  ),
);