<?php 
$setting['cate_models']['childcomm']=array (
  'id' => '12',
  'name' => 'childcomm',
  'description' => '子话题评论',
  'perpage' => '12',
  'level' => '1',
  'hasattach' => '0',
  'built_in' => '0',
  'fields' => 
  array (
    78 => 
    array (
      'id' => '78',
      'name' => 'fromid',
      'description' => '被评论话题',
      'model' => '12',
      'type' => 'select_from_model',
      'length' => '0',
      'values' => 'childtopic|title',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    79 => 
    array (
      'id' => '79',
      'name' => 'commid',
      'description' => '评论人',
      'model' => '12',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    80 => 
    array (
      'id' => '80',
      'name' => 'content',
      'description' => '评论内容',
      'model' => '12',
      'type' => 'wysiwyg',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    81 => 
    array (
      'id' => '81',
      'name' => 'time',
      'description' => '评论时间',
      'model' => '12',
      'type' => 'datetime',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '78',
    1 => '79',
    2 => '80',
    3 => '81',
  ),
  'searchable' => 
  array (
    0 => '78',
    1 => '79',
    2 => '80',
    3 => '81',
  ),
);