<?php 
$setting['cate_models']['art_comm']=array (
  'id' => '13',
  'name' => 'art_comm',
  'description' => '文章评论',
  'perpage' => '12',
  'level' => '1',
  'hasattach' => '0',
  'built_in' => '0',
  'fields' => 
  array (
    71 => 
    array (
      'id' => '71',
      'name' => 'fromid',
      'description' => '被评论文章id',
      'model' => '13',
      'type' => 'int',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    72 => 
    array (
      'id' => '72',
      'name' => 'comeid',
      'description' => '评论人id',
      'model' => '13',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    73 => 
    array (
      'id' => '73',
      'name' => 'content',
      'description' => '评论内容',
      'model' => '13',
      'type' => 'wysiwyg',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
    74 => 
    array (
      'id' => '74',
      'name' => 'time',
      'description' => '评论时间',
      'model' => '13',
      'type' => 'datetime',
      'length' => '0',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '0',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '71',
    1 => '72',
    2 => '73',
    3 => '74',
  ),
  'searchable' => 
  array (
    0 => '71',
    1 => '72',
    2 => '73',
    3 => '74',
  ),
);