<?php 
$setting['category']['article']=array (
  15 => 
  array (
    'classid' => '15',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'title' => '电子商务B2B数据分析全流程',
    'content' => 'WEB1.0时代是纯媒体。2了之后（web2.0），社区这个名词越来越红。乱七八糟的产品都被喊做社区，乱七八 糟的社区都号称是,WEB1.0时代是纯媒体。2了之后，社区这个名词越来越红。乱七八糟的产品都被喊做社区，乱七八 糟的社区都号称是,WEB1.0时代是纯媒体。2了之后，社区这个名词越来越红。乱七八糟的产品都被喊做社区，乱七八 糟的社区都号称是.WEB1.0时代是纯媒体。2了之后，社区这个名词越来越红。乱七八糟的产品都被喊做社区，乱七八 糟的社区都号称是.WEB1.0时代是纯媒体。2了之后（web2.0），社区这个名词越来越红。乱七八糟的产品都被喊做社区，乱七八 糟的社区都号称是。<br />',
    'author' => 'me',
    'createtime' => '2012-02-08 13:03:34',
    'type' => '2',
    'virtue' => '0',
    'summary' => '乱七八糟的概念',
    'formal' => '0',
    'ispass' => '1',
    'ishot' => '1',
    'children' => '0',
    'deep' => 0,
  ),
  16 => 
  array (
    'classid' => '16',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'title' => '我的文章21',
    'content' => '内容1<br />',
    'author' => 'admin',
    'createtime' => '2012-02-08 14:49:05',
    'type' => '4',
    'virtue' => '0',
    'summary' => '摘要1',
    'formal' => '',
    'ispass' => '0',
    'ishot' => '',
    'children' => '0',
    'deep' => 0,
  ),
  17 => 
  array (
    'classid' => '17',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'title' => 'Relication技术深入 高性能KV数据库',
    'content' => '123<br />',
    'author' => 'guest',
    'createtime' => '2012-02-08 13:15:56',
    'type' => '1',
    'virtue' => '0',
    'summary' => 'test',
    'formal' => '0',
    'ispass' => '1',
    'ishot' => '1',
    'children' => '0',
    'deep' => 0,
  ),
  18 => 
  array (
    'classid' => '18',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'title' => '我的文章2',
    'content' => '内容<br />',
    'author' => 'admin',
    'createtime' => '2012-02-08 14:45:17',
    'type' => '0',
    'virtue' => '0',
    'summary' => '摘要',
    'formal' => '',
    'ispass' => '0',
    'ishot' => '',
    'children' => '0',
    'deep' => 0,
  ),
  19 => 
  array (
    'classid' => '19',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'title' => '121322323',
    'content' => '2332<br />',
    'author' => 'admin',
    'createtime' => '2012-02-08 14:56:49',
    'type' => '2',
    'virtue' => '0',
    'summary' => '233233',
    'formal' => '',
    'ispass' => '0',
    'ishot' => '',
    'children' => '0',
    'deep' => 0,
  ),
  20 => 
  array (
    'classid' => '20',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'title' => 'ci框架',
    'content' => 'ci框架是。。。<br />',
    'author' => 'guest',
    'createtime' => '2012-02-09 13:35:57',
    'type' => '1',
    'virtue' => '1',
    'summary' => 'ci框架',
    'formal' => '0',
    'ispass' => '0',
    'ishot' => '0',
    'children' => '0',
    'deep' => 0,
  ),
);