<?php 
$setting['category']['art_comm']=array (
  1 => 
  array (
    'classid' => '1',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromid' => '15',
    'comeid' => 'admin',
    'content' => '123',
    'time' => '2012-02-08 13:10:53',
    'children' => '0',
    'deep' => 0,
  ),
  2 => 
  array (
    'classid' => '2',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromid' => '15',
    'comeid' => 'admin',
    'content' => '鹅鹅鹅',
    'time' => '2012-02-08 13:56:05',
    'children' => '0',
    'deep' => 0,
  ),
  3 => 
  array (
    'classid' => '3',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromid' => '15',
    'comeid' => 'admin',
    'content' => '飞洒发是',
    'time' => '2012-02-08 14:06:24',
    'children' => '0',
    'deep' => 0,
  ),
  4 => 
  array (
    'classid' => '4',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromid' => '1',
    'comeid' => 'admin',
    'content' => NULL,
    'time' => '2012-02-08 14:07:30',
    'children' => '0',
    'deep' => 0,
  ),
  5 => 
  array (
    'classid' => '5',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromid' => '1',
    'comeid' => 'admin',
    'content' => '<a href=\'./\'>#MySQL Relication技术深入#</a>',
    'time' => '2012-02-08 14:12:01',
    'children' => '0',
    'deep' => 0,
  ),
  6 => 
  array (
    'classid' => '6',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromid' => NULL,
    'comeid' => 'admin',
    'content' => '123',
    'time' => '2012-02-08 16:55:39',
    'children' => '0',
    'deep' => 0,
  ),
  7 => 
  array (
    'classid' => '7',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromid' => NULL,
    'comeid' => 'admin',
    'content' => '123333',
    'time' => '2012-02-08 16:55:47',
    'children' => '0',
    'deep' => 0,
  ),
  8 => 
  array (
    'classid' => '8',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromid' => '17',
    'comeid' => 'admin',
    'content' => '12',
    'time' => '2012-02-08 16:56:21',
    'children' => '0',
    'deep' => 0,
  ),
  9 => 
  array (
    'classid' => '9',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromid' => '17',
    'comeid' => 'admin',
    'content' => 'lala',
    'time' => '2012-02-08 16:56:30',
    'children' => '0',
    'deep' => 0,
  ),
  10 => 
  array (
    'classid' => '10',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromid' => '15',
    'comeid' => 'guest',
    'content' => 'eeeeeeeeee',
    'time' => '2012-02-10 21:22:33',
    'children' => '0',
    'deep' => 0,
  ),
  11 => 
  array (
    'classid' => '11',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromid' => '15',
    'comeid' => 'mylecturer',
    'content' => '111111111111111',
    'time' => '2012-02-10 21:23:13',
    'children' => '0',
    'deep' => 0,
  ),
);