<?php 
$setting['category']['guanzhu']=array (
  1 => 
  array (
    'classid' => '1',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'slid' => '1',
    'name' => 'guest',
    'time' => '2012-02-11 10:11:17',
    'children' => '0',
    'deep' => 0,
  ),
  2 => 
  array (
    'classid' => '2',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'slid' => '3',
    'name' => 'guest',
    'time' => '2012-02-11 10:14:41',
    'children' => '0',
    'deep' => 0,
  ),
  3 => 
  array (
    'classid' => '3',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'slid' => '1',
    'name' => 'guest',
    'time' => '2012-02-11 10:22:05',
    'children' => '0',
    'deep' => 0,
  ),
  4 => 
  array (
    'classid' => '4',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'slid' => '1',
    'name' => 'guest',
    'time' => '2012-02-11 10:22:08',
    'children' => '0',
    'deep' => 0,
  ),
  5 => 
  array (
    'classid' => '5',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'slid' => '1',
    'name' => 'guest',
    'time' => '2012-02-11 10:22:09',
    'children' => '0',
    'deep' => 0,
  ),
  6 => 
  array (
    'classid' => '6',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'slid' => '1',
    'name' => 'guest',
    'time' => '2012-02-11 10:22:10',
    'children' => '0',
    'deep' => 0,
  ),
  7 => 
  array (
    'classid' => '7',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'slid' => '1',
    'name' => 'guest',
    'time' => '2012-02-11 10:22:12',
    'children' => '0',
    'deep' => 0,
  ),
  8 => 
  array (
    'classid' => '8',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'slid' => '1',
    'name' => 'guest',
    'time' => '2012-02-11 10:22:26',
    'children' => '0',
    'deep' => 0,
  ),
  9 => 
  array (
    'classid' => '9',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'slid' => '1',
    'name' => 'admin',
    'time' => '2012-02-11 10:22:53',
    'children' => '0',
    'deep' => 0,
  ),
  10 => 
  array (
    'classid' => '10',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'slid' => '1',
    'name' => 'admin',
    'time' => '2012-02-11 10:22:54',
    'children' => '0',
    'deep' => 0,
  ),
  11 => 
  array (
    'classid' => '11',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'slid' => '1',
    'name' => 'admin',
    'time' => '2012-02-11 10:22:55',
    'children' => '0',
    'deep' => 0,
  ),
);