<?php 
$setting['category']['childtopic']=array (
  1 => 
  array (
    'classid' => '1',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromsalon' => '1',
    'title' => 'MySQL Relication技术深入',
    'content' => ' 话题内容',
    'lecturer' => '4',
    'children' => '0',
    'deep' => 0,
  ),
  2 => 
  array (
    'classid' => '2',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromsalon' => '1',
    'title' => '飞信DB高可用框架及将来规划',
    'content' => '话题内容',
    'lecturer' => '0',
    'children' => '0',
    'deep' => 0,
  ),
  3 => 
  array (
    'classid' => '3',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromsalon' => '1',
    'title' => '配合zookeeper的快速切换与数据一致',
    'content' => '内容<br />',
    'lecturer' => '0',
    'children' => '0',
    'deep' => 0,
  ),
  4 => 
  array (
    'classid' => '4',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromsalon' => '3',
    'title' => '话题1',
    'content' => '话题1内容<br />',
    'lecturer' => '0',
    'children' => '0',
    'deep' => 0,
  ),
  5 => 
  array (
    'classid' => '5',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromsalon' => '3',
    'title' => '话题2',
    'content' => '2内容<br />',
    'lecturer' => '0',
    'children' => '0',
    'deep' => 0,
  ),
  6 => 
  array (
    'classid' => '6',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromsalon' => '3',
    'title' => '话题3',
    'content' => '3内容<br />',
    'lecturer' => '0',
    'children' => '0',
    'deep' => 0,
  ),
  7 => 
  array (
    'classid' => '7',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromsalon' => '4',
    'title' => '话题11',
    'content' => '11内容<br />',
    'lecturer' => '0',
    'children' => '0',
    'deep' => 0,
  ),
  8 => 
  array (
    'classid' => '8',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromsalon' => '4',
    'title' => '话题22',
    'content' => '22内容<br />',
    'lecturer' => '0',
    'children' => '0',
    'deep' => 0,
  ),
  9 => 
  array (
    'classid' => '9',
    'parentid' => '0',
    'level' => '1',
    'path' => NULL,
    'fromsalon' => '4',
    'title' => '话题33',
    'content' => '33内容<br />',
    'lecturer' => '0',
    'children' => '0',
    'deep' => 0,
  ),
);